---
# Install network packages

- name: unwanted packages are removed
  package:
    name: "{{ network_packages_remove }}"
    state: absent
  become: true
  when: network_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ network_packages_repos }}"
    state: "{{ network_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ network_packages_prereq }}"
    state: "{{ network_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ network_packages_install }}"
    state: "{{ network_packages_state }}"
  become: true
